source "https://rubygems.org"

gem "puma"
gem "sinatra", "~> 2.1"
gem "sinatra-contrib"

group :development, :test do
  gem "pry"
  gem "rspec", "~> 3.7"
  gem "capybara", "~> 2.15"
  gem "launchy"
end

