source "https://rubygems.org"

gem "puma"
gem "sinatra", "~> 2.1"
gem "sinatra-contrib"
gem "activerecord", "~> 4.2"
gem "sinatra-activerecord", "2.0.13"

group :development, :test do
  gem "pry"
end
